server:
  port: 8087


application:
  file:
    #path: /Users/simpolor/IdeaProjects/sample-springboot/sample-springboot-upload/src/main/resources/files
    path: C:\Users\Simpolor\IdeaProjects\sample-springboot\sample-springboot-upload\src\main\webapp\upload
