server:
  port: 8082

#spring:
#  datasource:
#    driverClassName: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/demo_db?serverTimezone=UTC
#    username: demo
#    password: demo

#jpa:
#  hibernate:
#    ddl-auto: validate
#  properties:
#    hibernate:
#      dialect: org.hibernate.dialect.MySQL5InnoDBDialect
#  show-sql: true # 실행 되는 SQL문을 보여줄지 설
#  database: mysql

# ddl-auto 옵션 설명
# - create : 기존 테이블 삭제 후 새로 생성
# - create-drop : create와 동일하나 종료시 drop
# - update : 변경된 부분만 반영
# - validate : 테이블과 엔티티가 정상 매핑되었는지 유효성 검사
# - none : 기본값. 아무일도 일어나지 않음
