
POST http://localhost:8087/student/upload
//Content-Length: 394
Content-Type: multipart/form-data; boundary=WebAppBoundary
//Referer: http://127.0.0.1:8087/

--WebAppBoundary
Content-Disposition: form-data; name="profile"; filename="/Users/simpolor/Downloads/simpolor_color.png"
Content-Type: image/png

--WebAppBoundary
Content-Disposition: form-data; name="name"
Content-Type: text/plain

hello world
--WebAppBoundary
Content-Disposition: form-data; name="grade"
Content-Type: text/plain

2
--WebAppBoundary
Content-Disposition: form-data; name="age"
Content-Type: text/plain

18
--WebAppBoundary--

###
